<!DOCTYPE html>
<!-- 
    Patrice Moracchini
    Assignment module 2.2 
    August 23, 2026.
    This is a HTML/PHP program to display a table built first in HTML,
    then uses PHP loops to add row and collumns. It uses also PHP to 
    generate random numbers to fill the table.
    -->
<html lang="en">
    
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Patrice's Table</title>
    <!-- add a link to the Oxanium font from Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oxanium">
    <!-- add CSS styling to the page -->

    <style>
        body {
        font-family: "Oxanium",Arial, sans-serif;
        font-size: 20px;
        color: black;
        text-shadow: 3px 3px 3px #ababab;
        background-color: lightgray;
        padding: 20px;
        }
        h1 {
        color: #6B2D3A;
        text-shadow: 3px 3px 3px #ababab;
        text-align: center;
        }
        h2 {
        text-align: center;
        margin-bottom: 100px;
        }
        /* add CSS styling to the table */
        table {
        border-collapse: collapse; /* removes the space between the borders of the table cells */
        margin: 0 auto; /* centers the table horizontally on the page */
        }
        th, td {
        border: 3px solid black;
        padding: 10px;
        text-align: center;
        }
    </style>

</head>

<body>
    <h1>Table in Almost PHP</h1>
    <h2>(well, just part of the table and the numbers)</h2>
    <!--  Table creation with the rows (tr) and columns (td) in HTML reapeate thanks
        to the PHP loop, and finally the numbers are generated by PHP -->
    <table>
        <?php
        for ($x =  1; $x <= 10; $x++){ 
        ?>
            <tr>  
            <?php
            for ($y =  1; $y <= 10; $y++) {
            ?>    
            <td><?php echo (rand(1,100)); ?></td>
            <?php
            }
            ?>
            </tr>
        <?php
}
?>
    </table>
</body>

</html>