<!DOCTYPE html>
<!-- 
    Patrice Moracchini
    Assignment module 3.2 
    August 23, 2026.
    This is a HTML/PHP program to display a table built first in HTML,
    then uses PHP loops to add row and columns. It uses also PHP to 
    generate random numbers Then call a function from an external file 
    to add those tow random numbers and ultimately fill the teble .
    -->
<html lang="en">
    
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Patrice's Table</title>

    <!-- add a link to the Oxanium font from Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oxanium">
   
    <!-- add CSS styling to the page -->
    <style>
        body {
        font-family: "Oxanium",Arial, sans-serif;
        font-size: 20px;
        color: black;
        text-shadow: 3px 3px 3px #ababab;
        background-color: lightgray;
        padding: 20px;
        }
        h1 {
        color: #6B2D3A;
        text-shadow: 3px 3px 3px #ababab;
        text-align: center;
        }
        h2 {
        text-align: center;
        margin-bottom: 100px;
        }
        /* add CSS styling to the table */
        table {
        border-collapse: collapse; /* removes the space between the borders of the table cells */
        margin: 0 auto; /* centers the table horizontally on the page */
        }
        th {
        border: 3px solid black;
        padding: 10px;
        text-align: center;
        background-color: #6B2D3A;
        color: white;
        text-shadow: none
    }
        td {
        border: 3px solid black;
        padding: 10px;
        text-align: center;
        }
    </style>
    <?php require 'PatriceTable3Function.php'; ?>
</head>

<body>
    <h1>Random Sum Table</h1>
    <h2>Using PHP and HTML<br> and calling a function on an external file</h2>
    <!--  Table creation with the rows (tr) and columns (td) in HTML repeat thanks
        to the PHP loop, and finally the numbers are generated by PHP -->
    <table>
        <tr>
            <!-- add a header row to the table -->
            <th colspan="10">Sum of 2 random numbers in each cell</th>  
</tr>
        <?php
        for ($x =  1; $x <= 10; $x++){ 
        ?>
            <tr>  
            <?php
            for ($y = 1; $y <= 10; $y++) {   
                $number1 = rand(1, 100);  // generate a random number between 1 and 100
                $number2 = rand(1, 100);  // and assign it to a variable 
            ?>    
            <!-- display the sum of the two random numbers in the table cell -->
            <td><?php echo (addNumbers($number1, $number2)); ?></td>
            <?php
            }
            ?>
            </tr>
        <?php
}
?>
    </table>
</body>

</html>